#!/usr/bin/env bash

date_format=$(date +"%Y.%m.%d")
dir_backup="/media/lm/lm-data/Backups"
text_end="\033[32;1mEnd successfully\033[0m"
text_fail="\033[31;1mFail\033[0m"

[[ -e /mnt/vmlinuz ]] && \
echo "Start backup linux on /mnt/ in /mnt/backup/backup_linux_$date_format.tar.gz" && \
cd /mnt && \
tar --exclude=tmp --exclude=home/lm/.cache --exclude=swapfile --exclude=backup -czpf \
/mnt/backup/backup_linux_$date_format.tar.gz ./ && \
echo -e $text_end || echo -e $text_fail

# LINUX RESTORE
#cd /mnt
#tar --numeric-owner -xzpf bacup.tar.gz
#dd if=/dev/zero of=/mnt/swapfile bs=1M count=8192
#mkswap /mnt/swapfile
#chmod 600 /mnt/swapfile
#ls -l /dev/disk/by-uuid
#vim /mnt/etc/fstab
#mount --bind /dev /mnt/dev
#mount --bind /proc /mnt/proc
#mount --bind /sys /mnt/sys
#chroot /mnt
#grub-insatll /dev/sdX
#update-grub --output=/boot/grub/grub.cfg'

# ANDROID WIFI ADB
#sudo setprop service.adb.tcp.port 5555
#sudo stop adbd
#sudo start adbd
