#!/usr/bin/env bash

mouse-key-exchange() {
    xinput get-button-map "RAPOO Rapoo 2.4G Wireless Device Mouse" |\
    grep "1 2 3 4 5 6 7 8 9" &>>/dev/null &&\
    xinput set-button-map "RAPOO Rapoo 2.4G Wireless Device Mouse" 3 2 1 4 5 6 7 8 9 ||\
    xinput set-button-map "RAPOO Rapoo 2.4G Wireless Device Mouse" 1 2 3 4 5 6 7 8 9
}

case $1 in
    -m|--mouse-key-exchange)
        mouse-key-exchange
        ;;
    -p|--pause-key)
        cd ./Downloads/
        ../.scripts/aunzip -up
        ;;
esac
