#!/usr/bin/env bash

case $1 in 
    -u|--unzip-with-name-and-date)
	while [ "$#" -ne "1" ] ; do
	    if [[ "$2" == *.zip ]] ; then
		echo "$2"
		new_name=$(echo "$2" | sed -e 's/\.zip//')
		mkdir "$new_name"
                unzip -j "$2" -d "./$new_name/"
	        if $(find "./$new_name/"*.txt &>/dev/null) ; then
		    rm "./$new_name/"*.txt	
		fi
		touch -r "$2" "$new_name"
                rm "$2"
            fi
        shift
        done
        ;;
    -up|--unzip-and-move-pdf)
        if [ -e ./*.zip ];then
            if [ -e ./*.pdf ];then
                arcive=$(echo ./*.zip)
                new_folder=$(echo "$arcive" | sed -e 's/\.zip//')
                mkdir "$new_folder"
                unzip -j "$arcive" -d "./$new_folder/"
                if $(find "./$new_folder/"*.txt &>/dev/null);then
                    rm "./$new_folder/"*.txt
                fi
                rm "$arcive"
                pdf=$(echo ./*.pdf)
                pdf_name=$(echo "$pdf" | sed -e 's/\.pdf//')
                mv "$pdf" "$new_folder"
                mv "$new_folder" "$pdf_name"
            fi
        fi
        ;;
    -m|--rename-from-pdf-in-folder)
        pdf=$(echo ./*/*.pdf)
        pdf_name=$(echo "$pdf" | sed -e 's/\.pdf//' -e 's|\./.*/||')
        mv ./*/ "$pdf_name"
        ;;
    -h|--help|*)
        echo "-u|--unzip-with-name-and-date"
        echo "-up|--unzip-and-move-pdf"
        echo "-h|--rename-from-pdf-in-folder"
        ;;
esac
