#!/usr/bin/env bash

case $1 in 
    -u|--unzip)
	while [ "$#" -ne "1" ] ; do
	    if [[ "$2" == *.zip ]] ; then
		echo "$2"
		new_name=$(echo "$2" | sed -e 's/\.zip//')
		mkdir "$new_name"
                unzip -j "$2" -d "./$new_name/"
	        if $(find "./$new_name/"*.txt &>/dev/null) ; then
		    rm "./$new_name/"*.txt	
		fi
		touch -r "$2" "$new_name"
                rm "$2"
            fi
        shift
        done
        ;;
    -um|--unzip-and-move-pdf)
        pwd
        arcive=$(echo ./Downloads/*.zip)
	new_name=$(echo "$arcive" | sed -e 's/\.zip//')
	mkdir "$new_name"
        unzip -j "$arcive" -d "./$new_name/"
        if $(find "./$new_name/"*.txt &>/dev/null) ; then
	    rm "./$new_name/"*.txt	
	fi
        rm "$arcive"
        mv ./Downloads/*.pdf "$new_name"
        echo "$arcive"
        echo "$new_name"
        ;;
    -h|--help|*)
        echo "-u|--unzip"
        ;;
esac  
